// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"effekseer_min","status":true,"description":"","parameters":{}},
{"name":"pixiEffekseer","status":true,"description":"","parameters":{}},
{"name":"EffekseerForRPGmakerMV","status":true,"description":"『Effekseer』forツクールMV(エフェクトツール)","parameters":{}}
];
